<a href="https://colab.research.google.com/github/dubuuri/aipython/blob/main/20240109.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MID TERM review

In [10]:
# 학생수준평가 시험에서 영어 점수와 수학 점수가 합해서 100점이 넘으면 합격(PASS)이지만, 한 과목 점수가 40점 미만이라면 과목 미달로 불합격(FAIL)이다.
# 영어, 수학 점수를 입력 받아 합격여부를 출력한다.

# 입력 : 첫번째 입력값이 영어점수 두번째 입력값이 수학점수이다.
# 출력 : 각 점수에 따라 결과가 다르게 출력된다.

a, b = map(int,input().split())

if a > 40 and b > 40 :
  if a + b > 100 :
    print("PASS")
  else :
    print("FAIL")
elif a > 40 and b < 40 :
  print("MATH FAIL")
elif a < 40 and b > 40 :
  print("ENG FAIL")
else :
  print("FAIL")

45 45
FAIL


In [14]:
# N개의 숫자가 공백없이 입력된다. 이 숫자를 모두 합쳐서 합을 출력하는 프로그램을 작성하시오

# 입력 : 첫째 줄에 숫자 N개가 공백없이 주어진다
# 출력 : 입력으로 주어진 숫자 N개의 합을 출력한다.

n = list(map(int,input()))
print(sum(n))

9876451
40


In [21]:
# 다음 리스트에서 확장자가 png나 jpg 인 파일명일 때, 확장자를 출력하는 파이썬 코드를 작성하세요.

n = int(input())
a = []

for i in range(n) :
  s = input()
  p = list(s.split("."))
  if "jpg" in p or "png" in p :
    a.append(s)
print(a)

3
naver.com
d.png
s.jpg
['d.png', 's.jpg']


# 넘파이 실습

In [22]:
import numpy as np

n = np.arange(1,10,2)
print(n)

[1 3 5 7 9]


In [23]:
import numpy as np

n = np.ones((3,4))
print(n)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
import numpy as np

n = np.linspace(0,1,10)
print(n)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [26]:
import numpy as np

a = np.arange(1,26).reshape(5,5)
print(a)
print(a.shape)
print(a[3,3])
print(a[0,0:2], a[1,0:2])
print(a[3,3:5], a[4,3:5])
print(a[0], a[1])
print(a[0,3:5],a[1,3:5],a[2,3:5],a[3,3:5],a[4,3:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)
19
[1 2] [6 7]
[19 20] [24 25]
[1 2 3 4 5] [ 6  7  8  9 10]
[4 5] [ 9 10] [14 15] [19 20] [24 25]


In [ ]:
a = np.arange(1,37).reshape(3,3,4)

print(a)
print(a.shape, a.ndim)
print(a.reshape(3,4,3))
print(a.reshape(36))